version: '3.8'

services:
  database:
    image: postgres:15
    container_name: eduplanner-database
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-test_user}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-root123}
      POSTGRES_DB: ${POSTGRES_DB:-edudb}
    volumes:
      - ${DB_DATA_VOLUME:-/srv/test/db_data}:/var/lib/postgresql/data
      - ../eduplanner-database/edudb.sql:/docker-entrypoint-initdb.d/edudb.sql
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "${POSTGRES_USER:-test_user}"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    build:
      context: ../eduplanner-server
    container_name: eduplanner-backend
    environment:
      SPRING_PROFILES_ACTIVE: ${SPRING_PROFILES_ACTIVE:-test}
      POSTGRES_USER: ${POSTGRES_USER:-test_user}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-root123}
      POSTGRES_DB: ${POSTGRES_DB:-edudb}
      DATABASE_URL: jdbc:postgresql://database:5432/${POSTGRES_DB:-edudb}
    depends_on:
      database:
        condition: service_healthy
    ports:
      - "8080:8080"

volumes:
  db_data:
