version: "3.8"
services:
  database:
    image: postgres:14
    container_name: ${CONTAINER_NAME_DATABASE:-eduplanner-database-dev}
    environment:
      POSTGRES_USER: ${DB_USERNAME:-root}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-root123}
      POSTGRES_DB: ${DB_NAME:-root}
    volumes:
      - ${DB_DATA_VOLUME_TEST:-/srv/test/db_data}:/var/lib/postgresql/data
    ports:
      - "${DB_PORT:-5432}:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${DB_USERNAME:-root}" ]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - dev_network
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ${CONTAINER_NAME_BACKEND:-eduplanner-backend-dev}
    environment:
      SPRING_PROFILES_ACTIVE: test
      SPRING_DATASOURCE_URL: jdbc:postgresql://database:5432/${DB_NAME:-eduplanner}
      SPRING_DATASOURCE_USERNAME: ${DB_USERNAME:-root}
      SPRING_DATASOURCE_PASSWORD: ${DB_PASSWORD:-root123}
    depends_on:
      database:
        condition: service_healthy
    ports:
      - "${BACKEND_PORT:-8081}:8080"
    networks:
      - dev_network
networks:
  dev_network:
    driver: bridge