services:
  database:
    image: postgres:latest
    container_name: eduplanner-database
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root123
      POSTGRES_DB: eduplanner
    volumes:
      - ./edudb.sql:/docker-entrypoint-initdb.d/edudb.sql
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "${POSTGRES_USER:-root}"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    build:
      context: .
    container_name: eduplanner-backend
    environment:
      SPRING_PROFILES_ACTIVE: ${SPRING_PROFILES_ACTIVE:-test}
      POSTGRES_USER: ${POSTGRES_USER:-root}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-root123}
      POSTGRES_DB: ${POSTGRES_DB:-eduplanner}
      DATABASE_URL: jdbc:postgresql://database:5432/${POSTGRES_DB:-eduplanner}
    depends_on:
      database:
        condition: service_healthy
    ports:
      - "8080:8080"

volumes:
  db_data:
