services:
  database:
    image: postgres:14
    container_name: eduplanner-database-dev
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root123
      POSTGRES_DB: edudb
    volumes:
      - eduplanner-db-data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    ports:
      - "${DB_PORT:-5432}:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U root -d edudb" ]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - dev_network
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ${CONTAINER_NAME_BACKEND:-eduplanner-backend-dev}
    environment:
     SPRING_DATASOURCE_URL: jdbc:postgresql://eduplanner-database-dev:5432/edudb
     SPRING_DATASOURCE_USERNAME: root
     SPRING_DATASOURCE_PASSWORD: root123
    depends_on:
      database:
        condition: service_healthy
    ports:
      - "${BACKEND_PORT:-8081}:8081"
    networks:
      - dev_network

networks:
  dev_network:
    driver: bridge

volumes:
  eduplanner-db-data: {}
