version: "3.8"

services:
  database:
    image: postgres:14
    container_name: eduplanner-database-dev
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root123
      POSTGRES_DB: eduplanner
    volumes:
      - ${DB_DATA_VOLUME_TEST:-/srv/test/db_data}:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    ports:
      - "5433:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U root"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - dev_network



  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: eduplanner-backend-dev
    working_dir: /app
    volumes:
      - .:/app
      - gradle_cache:/home/gradle/.gradle
    environment:
      SPRING_PROFILES_ACTIVE: test
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root123
      POSTGRES_DB: eduplanner
      DATABASE_URL: jdbc:postgresql://database:5432/eduplanner
    depends_on:
      database:
        condition: service_healthy
    ports:
      - "8081:8080"
    networks:
      - dev_network



volumes:
  gradle_cache:
    name: dev_gradle_cache

networks:
  dev_network:
    driver: bridge
