name: CI Pipeline

on:
  push:
    branches:
      - main
      - dev
  pull_request:
    branches:
      - main
      - dev

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: '17'  # Wersja JDK, której używasz
          distribution: 'temurin'  # Możesz wybrać temurin, zulu, itd.

      - name: Build project
        run: ./gradlew build

      - name: Run tests
        run: ./gradlew test
