name: CI/CD Pipeline for Backend and Database

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  integration-tests:
    name: Run Integration Tests
    runs-on: ubuntu-latest

    env:
      DB_DATA_VOLUME: /srv/test/db_data
      SPRING_PROFILES_ACTIVE: test
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root123
      POSTGRES_DB: eduplanner

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set Up Docker Compose
        run: |
          docker-compose -f ./docker-compose.yml down -v || true
          docker-compose -f ./docker-compose.yml up -d

      - name: Wait for Database to Be Ready
        run: |
          for i in {1..10}; do
            docker exec eduplanner-database-dev pg_isready -U root && exit 0 || sleep 5
          done
          exit 1

      - name: Check Logs for Debugging
        run: |
          docker logs eduplanner-database-dev || true

      - name: Run Tests
        run: |
          docker exec eduplanner-backend-dev gradle test --no-daemon

      - name: Tear Down Docker Compose
        if: always()
        run: docker-compose -f ./docker-compose.yml down -v
