name: CI Pipeline

on:
  push:
    branches:
      - dev
  pull_request:
    branches:
      - dev

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set environment variables
        run: |
          echo "DB_DATA_VOLUME=/srv/test/db_data" >> $GITHUB_ENV
          echo "SPRING_PROFILES_ACTIVE=test" >> $GITHUB_ENV
          echo "POSTGRES_USER=root" >> $GITHUB_ENV
          echo "POSTGRES_PASSWORD=root123" >> $GITHUB_ENV
          echo "POSTGRES_DB=eduplanner" >> $GITHUB_ENV

      - name: Ensure data directory is clean
        run: docker volume rm eduplanner-server_db_data || true

      - name: Remove existing containers
        run: docker-compose -f ./docker-compose.yml down -v || true

      - name: Install Docker Compose
        run: |
          curl -SL https://github.com/docker/compose/releases/download/v2.22.0/docker-compose-$(uname -s)-$(uname -m) -o /usr/local/bin/docker-compose
          chmod +x /usr/local/bin/docker-compose

      - name: Prune Docker System
        run: docker system prune -af || true

      - name: Start services with Docker Compose
        run: docker-compose -f ./docker-compose.yml up -d

      - name: Run Tests
        run: ./gradlew test

      - name: Fetch Database Logs
        if: failure()
        run: docker logs eduplanner-database || true

      - name: Fetch Backend Logs
        if: failure()
        run: docker logs eduplanner-backend || true

      - name: Stop and remove services
        if: always()
        run: docker-compose -f ./docker-compose.yml down
